src/java/co/formulariosintomas/bean/OpcionPregunta.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.formulariosintomas.bean;

import java.util.Date;

/**
 *
 * @author David
 */
public class OpcionPregunta {

    private Long idOpcionPregunta;
    private Pregunta idPregunta;
    private String codigo;
    private String descripcion;
    private String estado;
    private Date fechaCreacion;
    private Date fechaModificacion;

    public OpcionPregunta() {
        this.fechaCreacion = new Date();
        this.fechaModificacion = new Date();
        this.idPregunta = new Pregunta();
    }

    public Long getIdOPcionPregunta() {
        return idOpcionPregunta;
    }

    public void setIdOPcionPregunta(Long idOpcionPregunta) {
        this.idOpcionPregunta = idOpcionPregunta;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Date getFechaModificacion() {
        return fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    public Pregunta getIdPregunta() {
        return idPregunta;
    }

    public void setIdPregunta(Pregunta idPregunta) {
        this.idPregunta = idPregunta;
    }

}

web/secciones/botonesFormulario.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
    <div>
        <p:commandButton rendered="#{formularioSintomasMB.formularioTablaIndividualRendered}" icon="fa fa-arrow-left" actionListener="#{formularioSintomasMB.volverTabla()}" id="btMenuVolverTabla" value="#{msg['button.regresar']}"  update=":frmFormulario" />
        <p:commandButton rendered="#{formularioSintomasMB.botonRegresar}" icon="fa fa-arrow-left" actionListener="#{formularioSintomasMB.volverMenuPrincipal()}" id="btMenuVolverInicio2" value="#{msg['button.regresar']}"  update=":frmFormulario" process="@this"/>
        <p:commandButton rendered="#{formularioSintomasMB.botonRegresarTablaTemperatura}" icon="fa fa-arrow-left" actionListener="#{formularioSintomasMB.regresarTablaTemperatura()}" id="btVolverTemperatura" value="#{msg['button.regresar']}"  update=":frmFormulario" process="@this"/>
        <p:commandButton rendered="#{formularioSintomasMB.botonGuardarFormulario}"  icon="fa fa-save" action="#{formularioSintomasMB.guardarFormulario()}" id="btMenuGuardar" value="#{msg['button.guardar.formulario']}" update=":frmFormulario"/>
        <p:commandButton rendered="#{formularioSintomasMB.menuAdministradorOpcionUno and (formularioSintomasMB.tipoUsuario eq formularioSintomasMB.adm)}" icon="fa fa-download" value="Exportar Tabla a Excel" ajax="false" style="width: 25%;">
            <p:dataExporter type="xls" target="tbladm" fileName="personas"/>
        </p:commandButton>
<!--        <p:commandButton rendered="{formularioSintomasMB.menuAdministradorOpcionDos and (formularioSintomasMB.tipoUsuario eq formularioSintomasMB.adm) and formularioSintomasMB.formularioTablaIndividualRendered == false}" icon="fa fa-download" value="Exportar Tabla a Excel" ajax="false" style="width: 25%;">
            <p:dataExporter type="xls" target="tbladmsegundo" fileName="personas"/>
        </p:commandButton>-->
    </div>

</ui:composition>

web/secciones/cambiarContrasena.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">


    <p:panel id="panelContrasena" rendered="#{formularioSintomasMB.cambioContrasena}" header="Cambiar Contraseña" style="text-align: center; display: inline-block">
        <h:panelGrid  columns="3" cellpadding="1" columnClasses="p-col-12 p-md-6 p-lg-3, p-col-12 p-md-6 p-lg-3, p-col-12 p-md-6 p-lg-3, p-col-12 p-md-6 p-lg-3">           
            <p:outputLabel for="pass1" class="labelNegrilla"  value="#{msg['label.nueva.contrasena']}"/>
            <p:password id="pass1" value="#{formularioSintomasMB.nuevaContrasena}" required="true" feedback="true" validatorMessage="Falta Contraseña"/>
            <p:tooltip style="font-size: 12px" for="pass1">#{msg['label.nueva.contrasena']}</p:tooltip>
            <p:outputLabel for="pass2" class="labelNegrilla"  value="#{msg['label.repetir.contrasena']}"/>
            <p:password id="pass2" value="#{formularioSintomasMB.confirmaContrasena}" required="true" feedback="true" validatorMessage="Falta Contraseña"/>
            <p:tooltip style="font-size: 12px" for="pass2">#{msg['label.repetir.contrasena']}</p:tooltip>                
            <p:commandButton action="#{formularioSintomasMB.cambiarContrasena()}" value="#{msg['button.confirma.contraseña']}" update=":frmFormulario"></p:commandButton>
        </h:panelGrid>

    </p:panel>

</ui:composition>


web/secciones/cambiarContrasenaAdministrador.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">


    <p:panel id="panelContrasenaAdm" rendered="#{formularioSintomasMB.renderedActivarCambioContrasena}" header="Cambiar Contraseña" style="text-align: center; display: inline-block">
        <h:panelGrid  columns="3" cellpadding="1" columnClasses="p-col-12 p-md-6 p-lg-3, p-col-12 p-md-6 p-lg-3, p-col-12 p-md-6 p-lg-3, p-col-12 p-md-6 p-lg-3">           
            <p:outputLabel for="itxIdentificacionInfPersonaladm" class="labelNegrilla" value="#{msg['label.identificacion']}"/>
            <p:inputText id="itxIdentificacionInfPersonaladm" class="dimencionLabel" value="#{formularioSintomasMB.identificacionContrasena}" required="true" />
            <p:tooltip style="font-size: 12px" for="itxIdentificacionInfPersonaladm">#{msg['label.identificacion']}</p:tooltip>
            <p:outputLabel for="pass1adm" class="labelNegrilla"  value="#{msg['label.nueva.contrasena']}"/>
            <p:password id="pass1adm" value="#{formularioSintomasMB.nuevaContrasena}" required="true" feedback="true" validatorMessage="Falta Contraseña"/>
            <p:tooltip style="font-size: 12px" for="pass1adm">#{msg['label.nueva.contrasena']}</p:tooltip>
            <p:outputLabel for="pass2adm" class="labelNegrilla"  value="#{msg['label.repetir.contrasena']}"/>
            <p:password id="pass2adm" value="#{formularioSintomasMB.confirmaContrasena}" required="true" feedback="true" validatorMessage="Falta Contraseña"/>
            <p:tooltip style="font-size: 12px" for="pass2adm">#{msg['label.repetir.contrasena']}</p:tooltip>                
            <p:commandButton action="#{formularioSintomasMB.cambiarContrasenaAdmin()}" value="#{msg['button.confirma.contraseña']}" update=":frmFormulario"></p:commandButton>
        </h:panelGrid>

    </p:panel>

</ui:composition>


web/secciones/cambioRolPersonasRegistradas.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:panelGrid  columns="2"  rendered="#{formularioSintomasMB.menuManejoRolRedered}" style="margin-top: 3%;" columnClasses="ui-grid-col-12" layout="grid" styleClass="ui-panelgrid-blank form-group">
        <p:dataTable id="tblseguridad" var="reg" value="#{formularioSintomasMB.listTablaManejoRol}"
                     paginator="true" rows="10" 
                     filteredValue="#{formularioSintomasMB.listTablaManejoRolFiltro}"  
                     emptyMessage="#{mensaje['formulario.tabla.vacio']}" >


            <p:column  headerText="Identificación" filterBy="#{reg.idUsuario.identificacion}">
                <h:outputText value="#{reg.idUsuario.identificacion}" />
            </p:column>

            <p:column headerText="Nombre" filterBy="#{reg.idUsuario.usuario}">
                <h:outputText value="#{reg.idUsuario.usuario}" />
            </p:column>

            <p:column headerText="Email" filterBy="#{reg.idUsuario.email}">
                <h:outputText value="#{reg.idUsuario.email}" />
            </p:column>

            <p:column headerText="Usuario" exportable="false">
                <p:selectBooleanCheckbox value="#{reg.idUsuario.rolUsuario}" >                    
                    <p:ajax  listener="#{formularioSintomasMB.editarRolesPersona(reg,'Usuario')}" />
                </p:selectBooleanCheckbox>
            </p:column>

            <p:column headerText="Administrador" exportable="false">
                <p:selectBooleanCheckbox value="#{reg.idUsuario.rolAdministrador}" >                    
                    <p:ajax   listener="#{formularioSintomasMB.editarRolesPersona(reg,'Administrador')}" />
                </p:selectBooleanCheckbox>
            </p:column>

            <p:column headerText="Consulta" exportable="false">
                <p:selectBooleanCheckbox value="#{reg.idUsuario.rolConsulta}" >                    
                    <p:ajax  listener="#{formularioSintomasMB.editarRolesPersona(reg,'Consulta')}" />
                </p:selectBooleanCheckbox>
            </p:column>
        </p:dataTable>

    </p:panelGrid>


</ui:composition>

web/secciones/errorLoginMicrosoft.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    template="../templates/template.xhtml">

    <ui:define name="title">#{msg['label.titulo']}</ui:define>

    <ui:define name="content">
        <h:form id="frmFormulario">
            <p:growl id="growl" showDetail="true" sticky="true" showSummary="false" class="mensaje" />  
            <div class="ui-fluid">
                <p:panelGrid>
                    <div class="ui-g-12 " style="background: local;
                         justify-content: center;
                         text-align: center;
                         font-weight: bold;
                         font-size: large;">
                        <p>
                            #{mensaje['error.login']}
                        </p>      
                    </div>
                </p:panelGrid> 
            </div>
            <div class="ui-g-12 button-container">

            </div> 
        </h:form>
    </ui:define>


</ui:composition>

web/secciones/errorLoginMicrosoftIden.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    template="../templates/template.xhtml">

    <ui:define name="title">#{msg['label.titulo']}</ui:define>

    <ui:define name="content">
        <h:form id="frmFormulario">
            <p:growl id="growl" showDetail="true" sticky="true" showSummary="false" class="mensaje" />  
            <div class="ui-fluid">
                <p:panelGrid>
                    <div class="ui-g-12 " style="background: local;
                         justify-content: center;
                         text-align: center;
                         font-weight: bold;
                         font-size: large;">
                        <p>
                            #{mensaje['error.identificacion']}
                        </p>      
                    </div>
                </p:panelGrid> 
            </div>
            <div class="ui-g-12 button-container">

            </div> 
        </h:form>
    </ui:define>


</ui:composition>

web/secciones/errorVariasEncuestas.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    template="../templates/template.xhtml">

    <ui:define name="title">#{msg['label.titulo']}</ui:define>

    <ui:define name="content">
        <h:form id="frmFormulario">
            <p:growl id="growl" showDetail="true" sticky="true" showSummary="false" class="mensaje" />  
            <div class="ui-fluid">
                <p:panelGrid>
                    <div class="ui-g-12 " style="background: local;
                         justify-content: center;
                         text-align: center;
                         font-weight: bold;
                         font-size: large;">
                        <p>
                            #{mensaje['error.varias.encuestas']} 
                        </p>      
                    </div>
                </p:panelGrid> 
            </div>
            <div class="ui-g-12 button-container">
                <ui:include src="./../secciones/botonesFormulario.xhtml"/>
            </div> 
        </h:form>
    </ui:define>


</ui:composition>

web/secciones/footer_piePagina.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
        <div class="notas">
            <p><em>Al enviar este formulario autorizo, expresamente y de manera voluntaria, a la Fundación Universitaria Konrad Lorenz para usar y manejar los datos que he suministrado, con propósitos académicos y según la siguiente 
                    <a href="http://www.konradlorenz.edu.co/es/informacion-institucional/nueva-imagen-institucional-2politicas-para-el-tratamiento-de-datos-personales.html" target="_blank" style="color:black;">política de tratamiento de datos personales.</a>  </em> </p>
        </div>
</ui:composition>

web/secciones/menuPrincipal.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:p="http://primefaces.org/ui">

    <p:menubar rendered="#{formularioSintomasMB.menuRendered}">
        <p:submenu label="#{msg['menu.encuesta']}" icon="fa fa-pencil" rendered="#{!formularioSintomasMB.menuConsulta}">
            <p:menuitem value="#{msg['menu.subencuesta']}" action="#{formularioSintomasMB.habilitarFormularioCovid()}"  update=":frmFormulario" rendered="#{formularioSintomasMB.menuUsuario}"/>
            <p:menuitem value="#{msg['menu.subencuesta']}" action="#{formularioSintomasMB.habilitarRegistroEnviadosAdministrador()}"  update=":frmFormulario" rendered="#{formularioSintomasMB.menuAdministrador}"/>
        </p:submenu>

        <p:submenu label="#{msg['menu.registro']}" icon="fa fa-file">
            <p:menuitem value="#{msg['menu.subregistro']}" action="#{formularioSintomasMB.habilitarRegistroEnviados()}" update=":frmFormulario" rendered="#{formularioSintomasMB.menuUsuario}"/>
            <p:menuitem value="#{msg['menu.subconsulta']}" action="#{formularioSintomasMB.habilitarConsultarRegistros()}"  update=":frmFormulario" rendered="#{formularioSintomasMB.menuAdministrador || formularioSintomasMB.menuConsulta}" />
        </p:submenu>

        <p:submenu label="#{msg['menu.temperatura']}" icon="fa fa-pencil" rendered="#{formularioSintomasMB.menuConsulta}">
            <p:menuitem value="#{msg['menu.subtemperatura']}" action="#{formularioSintomasMB.habilitarTemperatura()}" update=":frmFormulario" rendered="#{formularioSintomasMB.menuConsulta}"/>
        </p:submenu>

        <p:submenu label="#{msg['menu.roles']}" icon="fa fa-pencil" rendered="#{formularioSintomasMB.menuAdministrador}">
            <p:menuitem value="#{msg['menu.subroles']}" action="#{formularioSintomasMB.habilitarEditarRoles()}" update=":frmFormulario" rendered="#{formularioSintomasMB.menuAdministrador}"/>
        </p:submenu>

        <p:submenu label="#{msg['menu.cambio.contrasena']}" icon="fa fa-pencil" rendered="#{formularioSintomasMB.menuAdministrador}">
            <p:menuitem value="#{msg['menu.cambio.contrasena']}" action="#{formularioSintomasMB.habilitarCambioContrasena()}" update=":frmFormulario" rendered="#{formularioSintomasMB.menuAdministrador}"/>
        </p:submenu>

        <p:submenu label="#{msg['menu.activacion']}" icon="fa fa-pencil" rendered="#{formularioSintomasMB.menuAdministrador || formularioSintomasMB.menuConsulta}">
            <p:menuitem value="#{msg['menu.activacion']}" action="#{formularioSintomasMB.habilitarActivacionPersonas()}" update=":frmFormulario" rendered="#{formularioSintomasMB.menuAdministrador || formularioSintomasMB.menuConsulta}">
            </p:menuitem>
        </p:submenu>


        <p:submenu label="#{msg['menu.contrasena']}" icon="fa fa-pencil" rendered="#{formularioSintomasMB.usuarioRol.idUsuario.tipoUsuario == 'X'}">
            <p:menuitem value="#{msg['menu.subContrasena']}" action="#{formularioSintomasMB.habilitarCambioContraseña()}" update=":frmFormulario"/>
        </p:submenu>

        <p:submenu label="#{msg['menu.salir']}" icon="fa fa-sign-out">
            <p:menuitem value="#{msg['menu.salir']}" action="#{formularioSintomasMB.salir()}"/>
            <p:menuitem value="#{msg['menu.cambiarRol']}" action="#{formularioSintomasMB.cambiarRolVista()}" update=":frmFormulario" rendered="#{formularioSintomasMB.variosRoles}"/>
        </p:submenu>
    </p:menubar>
</ui:composition>

web/secciones/registroEnviadosTabla.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:panelGrid  columns="1"  rendered="#{formularioSintomasMB.formularioRegistroEnviados}" columnClasses="ui-grid-col-12" layout="grid" style="margin-top: 3%;" styleClass="ui-panelgrid-blank form-group">
        <p:dataTable id="tbl" var="reg" value="#{formularioSintomasMB.listTablaResultados}"
                     paginator="true"  rows="20" style="margin-bottom:20px"
                     paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
                     filteredValue="#{formularioSintomasMB.listTablaResultadosFiltro}"
                     emptyMessage="#{mensaje['formulario.tabla.vacio']}">

            <p:column  headerText="Identificación">
                <h:outputText value="#{reg.idUsuario.identificacion}" />
            </p:column>

            <p:column headerText="Nombre">
                <h:outputText value="#{reg.idUsuario.usuario}" />
            </p:column>

            <p:column headerText="Email">
                <h:outputText value="#{reg.idUsuario.email}" />
            </p:column>

            <p:column headerText="Fecha Registro" >
                <h:outputText  value="#{reg.strDate}" /> 
            </p:column>

            <p:column headerText="Fecha Ingreso" >
                <h:outputText  value="#{reg.strDateFin}" /> 
            </p:column>

            <p:column headerText="#{msg['formulario.riesgo']}">
                <h:inputText style="background-color: #{reg.color};width: 50%;" disabled="true" value="#{reg.color eq 'red' ? 'Peligro' : 'Normal'}"></h:inputText>
            </p:column>

            <p:column headerText="#{msg['valido']}" exportable="false" rendered="#{formularioSintomasMB.formularioRegistroEnviados}">
                <h:outputText value="#{reg.validoRegistro}" />
            </p:column>

            <p:column headerText="Mostrar Registro" exportable="false" rendered="#{formularioSintomasMB.formularioRegistroEnviados}">
                <p:commandButton action="#{formularioSintomasMB.mostrarRegistroGuardado(reg)}" value="Ver" update=":frmFormulario"></p:commandButton>
            </p:column>
        </p:dataTable>

        <!--        <h2>{msg['formulario.exportar']}</h2>
                <p:commandButton value="Export Table as Excel" ajax="false" style="width: 25%;">
                    <p:dataExporter type="xls" target="tbl" fileName="personas"/>
                </p:commandButton>-->

    </p:panelGrid>

</ui:composition>

web/secciones/registroEnviadosTablaAdministradorMenu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:panelGrid  columns="1" rendered="#{formularioSintomasMB.tablaMenuPrincipalAdministardor}" style="margin-top: 3%;" columnClasses="ui-grid-col-12" layout="grid" styleClass="ui-panelgrid-blank form-group">
        <p:dataTable id="tbladmr" var="reg" value="#{formularioSintomasMB.listTablaResultadosTemperaturaMenuP}"
                     paginator="true" rows="15"
                     paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
                     emptyMessage="#{mensaje['formulario.tabla.vacio']}">

            <p:column  headerText="Identificación">
                <h:outputText value="#{reg.idUsuario.identificacion}" />
            </p:column>

            <p:column headerText="Nombre">
                <h:outputText value="#{reg.idUsuario.usuario}" />
            </p:column>

            <p:column headerText="Email">
                <h:outputText value="#{reg.idUsuario.email}" />
            </p:column>

            <p:column headerText="Fecha Registro">
                <h:outputText  value="#{reg.strDate}" />
            </p:column>

            <p:column headerText="Fecha Ingreso">
                <h:outputText  value="#{reg.strDateFin}" /> 
            </p:column>
        </p:dataTable>

    </p:panelGrid>

</ui:composition>

web/secciones/registroEnvidosIndividual.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:p="http://primefaces.org/ui">

    <p:panelGrid  columns="1" rendered="#{formularioSintomasMB.formularioTablaIndividualRendered}" columnClasses="ui-grid-col-12,ui-grid-col-12" layout="grid" styleClass="ui-panelgrid-blank form-group" style="width:100%" >
        <h:column>
            <p><strong>#{msg['formulario.fecha.registro']}: </strong><h:outputText  value="#{formularioSintomasMB.fechaRegistro}" ><f:convertDateTime pattern="yyyy-MM-dd"/>  </h:outputText></p>  
        </h:column>
        <h:column>
            <p><strong>#{msg['nombre.persona']}: </strong>#{formularioSintomasMB.nombreTablaIndividual}</p>  
        </h:column>
        <h:column>
            <p><strong>#{msg['formulario.riesgo']}: </strong><h:inputText style="background-color: #{formularioSintomasMB.colorRiesgo};width: 10%;" disabled="true"></h:inputText></p>    
        </h:column>

        <!--        <h:column rendered="{formularioSintomasMB.renderedRecomendacionesCodigo}">
                    <p><em><strong>{msg['nota']}: </strong></em></p> 
                    <p>{msg['nota.primero']}</p> 
                </h:column>-->

        <ui:repeat var="preguntas" value="#{formularioSintomasMB.listDetalleRespuesta}">
            <p><strong>#{preguntas.idOpcionPregunta.idPregunta.enunciado}</strong></p>
            <p>#{msg['formulario.respuesta']} #{preguntas.idOpcionPregunta.descripcion}  #{preguntas.idOpcionPregunta.idOPcionPregunta.toString() eq '19' ? preguntas.otraVinculacion : ''}</p>
        </ui:repeat>

        <ui:repeat var="multiple" value="#{formularioSintomasMB.listDetalleRespuestaTemp}">
            <ui:fragment rendered="#{formularioSintomasMB.pintarPreguntasMultiple(multiple.idOpcionPregunta.idPregunta.idPregunta)}"> 
                <p><strong>#{multiple.idOpcionPregunta.idPregunta.enunciado}</strong></p>
                <ui:repeat var="respuesta" value="#{formularioSintomasMB.pintarRespuestaMultiple}">
                    <p>#{msg['formulario.respuesta']} #{respuesta}</p>
                </ui:repeat>
            </ui:fragment>
        </ui:repeat>
    </p:panelGrid>
</ui:composition>

web/secciones/timeout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"                
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui">
    <p:idleMonitor onactive="sessionTimeOutDialog.show();" timeout="1800000" />
    <p:dialog header="Sesión caducada" widgetVar="sessionTimeOutDialog" modal="true"  closable="false" width="400" visible="false">                
        <h:outputText value="La sesión ha caducado, pulse el botón Recargar para volver a acceder a la aplicación" style="text-align: justify" />
        <br></br>
        <br></br>
        <input id="btnRecargarAdmin" type="button" value="Recargar" onclick="window.location='#{facesContext.externalContext.requestContextPath}';" />
    </p:dialog>
</ui:composition>